CFLAGS := -I. 
CPPFLAGS := -DCOD_PLATFORM=COD_COCOA
LDFLAGS := -framework Cocoa -lm
OBJ := src/cocoa.o src/common.o src/font.o src/image.o src/stb-png.o

all: examples/font examples/image examples/skeleton

examples/font: $(OBJ)
examples/image: $(OBJ)
examples/skeleton: $(OBJ)

src/cocoa.o: src/cocoa.m
